apiVersion: v1
kind: Secret
metadata:
  name: appsecrets
data:
  user: {{.Values.user | b64enc}}
  name: {{.Values.name | b64enc}}
  password: {{.Values.password | b64enc}}
  host: {{.Values.host | b64enc }}
  port: {{.Values.port | b64enc }}